{
 "title": "Feedback Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last 10 analysed reviews",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, tonality, text FROM data_analyzed ORDER BY id DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "Number of reviews analysed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM data_analyzed LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of reviews",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Percentage of feedback analysed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN (SELECT COUNT(*) FROM data) = 0 THEN NULL \r\n        ELSE (SELECT COUNT(*) FROM data_analyzed) / (SELECT COUNT(*) FROM data) \r\n    END AS ratio;\r\n"
    }
   ]
  },
  {
   "title": "Tonality",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT tonality, COUNT(tonality) FROM data_analyzed GROUP BY tonality LIMIT 50 "
    }
   ]
  }
 ]
}