version: '3'
services:
  feedback-analysis-system:
    container_name: fas
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - fas-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fas-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - env/pgadmin.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - fas-network
    depends_on:
      - postgres

  grafana:
    container_name: grafana
    image: grafana/grafana
    env_file:
      - env/grafana.env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - fas-network
    depends_on:
      - postgres

volumes:
  postgres-data:
  grafana_data:
  pgadmin_data:

networks:
  fas-network:
    driver: bridge
